export enum Characters {
    MARIO = 'mario',
    DR_MARIO = 'dr_mario',
    LUIGI = 'luigi',
    BOWSER = 'bowser',
    PEACH = 'peach',
    YOSHI = 'yoshi',
    DK = 'dk',
    C_FALCON = 'c_falcon',
    GANONDORF = 'ganondort',
    FALCO = 'falco',
    FOX = 'fox',
    NESS = 'ness',
    ICE_CLIMBERS = 'ice_climbers',
    KIRBY = 'kirby',
    SAMUS = 'samus',
    ZELDA = 'zelda',
    LINK = 'link',
    Y_LINK = 'y_link',
    PICHU = 'pichu',
    PIKACHU = 'pikachu',
    JIGGLYPUFF = 'jigglypuff',
    MEWTWO = 'mewtwo',
    GAME_WATCH = 'game_watch',
    MARTH = 'marth',
    ROY = 'roy'
}
